// ─── Project data — extracted from Yuriy Rubanov CV (2025) ──────────────────
//
// All 50+ consulting projects completed from 2000 to present.
// Used on /projects (full list) and / (featured 6 highlighted items).

export type ProjectRegion =
  | 'CIS & Eastern Europe'
  | 'Western Europe'
  | 'Africa'
  | 'Asia & Pacific'
  | 'Middle East'
  | 'Americas'

export interface Project {
  id: string
  title: string
  airport: string
  location: string
  country: string
  region: ProjectRegion
  period: string
  year: number           // primary sort key (end year)
  role: string
  scope: string
  client?: string
  highlight?: boolean    // shown in FeaturedProjects on homepage
}

export const projects: Project[] = [
  // ── 2025 ────────────────────────────────────────────────────────────────────
  {
    id: 'atyrau-2025',
    title: 'Master Plan Preparation',
    airport: 'International Airport Atyrau',
    location: 'Atyrau',
    country: 'Kazakhstan',
    region: 'CIS & Eastern Europe',
    period: '06/2025 – ongoing',
    year: 2025,
    role: 'Project Manager, Traffic Forecast & Market Expert',
    scope: 'Full master plan preparation including traffic forecasting and market assessment.',
    highlight: true,
  },
  {
    id: 'philippines-ifc-2025',
    title: 'Technical Consultant to IFC (Part B)',
    airport: 'Puerto Princesa, Butuan-Bancasi, Cotabato & Kalibo Airports',
    location: 'Multiple locations',
    country: 'Philippines',
    region: 'Asia & Pacific',
    period: '01/2025 – ongoing',
    year: 2025,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic forecasting consultancy for IFC for four Philippine airports.',
    client: 'IFC (International Finance Corporation)',
    highlight: true,
  },
  {
    id: 'tashkent-ifc-2025',
    title: 'Comparative Analysis for New Gateway Hub Airport',
    airport: 'Tashkent New Gateway Hub International Airport',
    location: 'Tashkent',
    country: 'Uzbekistan',
    region: 'CIS & Eastern Europe',
    period: '02/2025 – 06/2025',
    year: 2025,
    role: 'Project Manager, Traffic Forecast Expert',
    scope: 'Comparative analysis and traffic forecasting for new international hub airport project.',
    client: 'IFC (International Finance Corporation)',
    highlight: true,
  },
  // ── 2024 ────────────────────────────────────────────────────────────────────
  {
    id: 'nantes-2024',
    title: 'Technical Consultancy Support for Bid Preparation',
    airport: 'Nantes Atlantique Airport',
    location: 'Nantes',
    country: 'France',
    region: 'Western Europe',
    period: '11/2024 – 01/2025',
    year: 2024,
    role: 'Traffic Forecast (Peak Hour) Expert',
    scope: 'Peak hour traffic forecasting in support of concession bid preparation.',
    highlight: true,
  },
  {
    id: 'cape-winelands-2024',
    title: 'Air Traffic Forecast — Review & Second Opinion',
    airport: 'Cape Winelands Airport',
    location: 'Cape Winelands',
    country: 'South Africa',
    region: 'Africa',
    period: '11/2024 – 12/2024',
    year: 2024,
    role: 'Traffic Forecast Expert',
    scope: 'Independent review and second opinion on air traffic forecast.',
  },
  {
    id: 'banjul-2024',
    title: 'Feasibility Study & Indicative Offer to Government',
    airport: 'Banjul International Airport',
    location: 'Banjul',
    country: 'The Gambia',
    region: 'Africa',
    period: '10/2024 – 12/2024',
    year: 2024,
    role: 'Traffic Forecast Expert',
    scope: 'Feasibility study and indicative offer to the Government of The Gambia.',
    highlight: true,
  },
  {
    id: 'natakhtari-2024',
    title: 'Technical Assessment — Transport Junction & Infrastructure',
    airport: 'Natakhtari Aerodrome Area',
    location: 'Natakhtari',
    country: 'Georgia',
    region: 'CIS & Eastern Europe',
    period: '11/2023 – 02/2024',
    year: 2024,
    role: 'Project Manager',
    scope: 'Technical assessment of transport junction and infrastructure placement for private investor.',
    client: 'Service Air (private investor)',
  },
  {
    id: 'vaziani-ifp-2024',
    title: 'Design of Instrument Flight Procedures & Airspace',
    airport: 'Vaziani Aerodrome',
    location: 'Tbilisi',
    country: 'Georgia',
    region: 'CIS & Eastern Europe',
    period: '01/2024 – 09/2024',
    year: 2024,
    role: 'Project Manager',
    scope: 'IFP and airspace design for Vaziani aerodrome.',
    client: 'Sakaeronavigatsia',
  },
  {
    id: 'new-tbilisi-2023',
    title: 'Runway Assessment for New Tbilisi Airport',
    airport: 'New Tbilisi Airport',
    location: 'Tbilisi',
    country: 'Georgia',
    region: 'CIS & Eastern Europe',
    period: '06/2023 – 08/2023',
    year: 2023,
    role: 'Project Manager',
    scope: 'Runway assessment study for the new international airport project.',
  },
  // ── 2023 ────────────────────────────────────────────────────────────────────
  {
    id: 'philippines-ifc-2023',
    title: 'Technical Consultant to IFC (Part A)',
    airport: 'Laguindingan, Bohol, Davao & Iloilo Airports',
    location: 'Multiple locations',
    country: 'Philippines',
    region: 'Asia & Pacific',
    period: '10/2023 – 10/2024',
    year: 2023,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic forecasting for four Philippine airports as IFC technical consultant.',
    client: 'IFC (International Finance Corporation)',
  },
  // ── 2022 ────────────────────────────────────────────────────────────────────
  {
    id: 'beauvais-2022',
    title: 'Technical Advisory for Seller',
    airport: 'Aéroport Paris-Beauvais',
    location: 'Beauvais',
    country: 'France',
    region: 'Western Europe',
    period: '07/2022 – 12/2022',
    year: 2022,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic forecast advisory support for seller in airport transaction.',
  },
  {
    id: 'brazil-2022',
    title: 'Consultancy in 6th Privatisation Round',
    airport: 'Foz do Iguaçu International & Teresina Airport',
    location: 'Foz do Iguaçu & Teresina',
    country: 'Brazil',
    region: 'Americas',
    period: '11/2022 – 02/2023',
    year: 2022,
    role: 'Market & Traffic Expert',
    scope: 'Traffic and market analysis for the 6th Brazilian airport privatisation round.',
  },
  {
    id: 'frankfurt-hahn-2022',
    title: 'Prefeasibility Study',
    airport: 'Frankfurt-Hahn Airport',
    location: 'Hahn',
    country: 'Germany',
    region: 'Western Europe',
    period: '01/2022 – 07/2022',
    year: 2022,
    role: 'Traffic Forecast Expert',
    scope: 'Prefeasibility study with traffic demand analysis for Frankfurt-Hahn Airport.',
    highlight: true,
  },
  {
    id: 'abuja-2022',
    title: 'Bid Preparation for Terminal Concession',
    airport: 'Nnamdi Azikiwe International Airport',
    location: 'Abuja',
    country: 'Nigeria',
    region: 'Africa',
    period: '07/2022 – 10/2022',
    year: 2022,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic forecasting for terminal concession bid preparation.',
  },
  // ── 2021 & 2020 ─────────────────────────────────────────────────────────────
  {
    id: 'muscat-2020',
    title: 'Claim Support',
    airport: 'Muscat International Airport & Salalah Airport',
    location: 'Muscat & Salalah',
    country: 'Oman',
    region: 'Middle East',
    period: '01/2020 – 04/2022',
    year: 2022,
    role: 'Market & Traffic Expert',
    scope: 'Market and traffic analysis in support of legal claim proceedings.',
  },
  {
    id: 'boryspil-fbo-2021',
    title: 'Prefeasibility Study for FBO Business',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '07/2021 – 08/2021',
    year: 2021,
    role: 'Project Manager',
    scope: 'Prefeasibility study for Fixed Base Operator (FBO) business development.',
  },
  {
    id: 'zhulyany-mro-2021',
    title: 'Market Survey of MRO Business',
    airport: 'Kyiv International Airport "Zhulyany"',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '06/2021 – 10/2021',
    year: 2021,
    role: 'Project Manager',
    scope: 'Market survey for MRO (Maintenance, Repair & Overhaul) business opportunities.',
  },
  {
    id: 'tokol-2021',
    title: 'Prefeasibility Study',
    airport: 'Tököl Airport',
    location: 'Tököl',
    country: 'Hungary',
    region: 'CIS & Eastern Europe',
    period: '02/2021 – 03/2021',
    year: 2021,
    role: 'Market & Traffic Expert',
    scope: 'Prefeasibility study for airport development.',
  },
  {
    id: 'odesa-airport-city-2021',
    title: 'Airport City Concept',
    airport: 'Odesa Airport',
    location: 'Odesa',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '10/2021 – 11/2021',
    year: 2021,
    role: 'Project Manager',
    scope: 'Development of an airport city concept for Odesa Airport.',
  },
  {
    id: 'sofia-business-plan-2020',
    title: 'Business Plan Update',
    airport: 'Sofia Airport',
    location: 'Sofia',
    country: 'Bulgaria',
    region: 'CIS & Eastern Europe',
    period: '06/2020 – 03/2021',
    year: 2021,
    role: 'Traffic Forecast Expert',
    scope: 'Business plan update including revised traffic forecasts.',
  },
  {
    id: 'zhulyany-strategy-2020',
    title: 'Market Study for Future Strategic Positioning',
    airport: 'Kyiv International Airport "Zhulyany"',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '02/2020 – 03/2021',
    year: 2021,
    role: 'Project Manager',
    scope: 'Comprehensive market study for strategic future positioning.',
  },
  {
    id: 'dnipro-concept-2019',
    title: 'Development Concept',
    airport: 'International Airport "Dnipro"',
    location: 'Dnipro',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '12/2019 – 04/2021',
    year: 2021,
    role: 'Project Manager',
    scope: 'Long-term airport development concept and strategic roadmap.',
  },
  {
    id: 'sofia-covid-2020',
    title: 'Covid-19 Recovery Concept',
    airport: 'Sofia Airport',
    location: 'Sofia',
    country: 'Bulgaria',
    region: 'CIS & Eastern Europe',
    period: '06/2020 – 08/2020',
    year: 2020,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic recovery scenarios and airport strategy during COVID-19 pandemic.',
  },
  {
    id: 'boryspil-consultancy-2019',
    title: 'Technical Consultancy Services',
    airport: 'Boryspil International Airport',
    location: 'Boryspil',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '12/2019 – 03/2020',
    year: 2020,
    role: 'Project Manager',
    scope: 'General technical consultancy advisory services.',
  },
  // ── 2019 ────────────────────────────────────────────────────────────────────
  {
    id: 'ufa-masterplan-2019',
    title: 'Master Plan Update',
    airport: 'Ufa International Airport',
    location: 'Ufa',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '06/2019 – 02/2020',
    year: 2019,
    role: 'Project Manager',
    scope: 'Comprehensive master plan update for Ufa International Airport.',
  },
  {
    id: 'sofia-bid-review-2019',
    title: 'Bid Review',
    airport: 'Sofia Airport',
    location: 'Sofia',
    country: 'Bulgaria',
    region: 'CIS & Eastern Europe',
    period: '08/2019 – 11/2019',
    year: 2019,
    role: 'Traffic Forecast Expert',
    scope: 'Independent review of bid submissions with traffic forecast assessment.',
  },
  {
    id: 'toluca-2019',
    title: 'Traffic Forecast',
    airport: 'Toluca International Airport',
    location: 'Toluca',
    country: 'Mexico',
    region: 'Americas',
    period: '06/2019 – 07/2019',
    year: 2019,
    role: 'Traffic Forecast Expert',
    scope: 'Standalone traffic demand forecast study.',
  },
  {
    id: 'tallinn-feasibility-2018',
    title: 'Feasibility Study — Passenger Terminal & Apron Areas',
    airport: 'Tallinn Airport',
    location: 'Tallinn',
    country: 'Estonia',
    region: 'Western Europe',
    period: '07/2018 – 07/2019',
    year: 2019,
    role: 'Project Manager',
    scope: 'Full feasibility study for passenger terminal expansion and apron development.',
  },
  {
    id: 'dnipro-market-2019',
    title: 'Market Study for Future Strategic Positioning',
    airport: 'International Airport "Dnipro"',
    location: 'Dnipro',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '01/2019 – 03/2019',
    year: 2019,
    role: 'Project Manager',
    scope: 'Market study for long-term strategic positioning.',
  },
  {
    id: 'boryspil-hotel-2018',
    title: 'Search for a Hotel Operator',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '10/2018 – 07/2019',
    year: 2019,
    role: 'Project Manager',
    scope: 'Market sounding and operator search for an airport hotel development.',
  },
  // ── 2018 ────────────────────────────────────────────────────────────────────
  {
    id: 'montenegro-2018',
    title: 'Traffic Study for Montenegro',
    airport: 'Tivat & Podgorica Airport',
    location: 'Tivat & Podgorica',
    country: 'Montenegro',
    region: 'Western Europe',
    period: '09/2018 – 09/2018',
    year: 2018,
    role: 'Traffic Forecast Expert',
    scope: 'National traffic study covering both airports.',
  },
  {
    id: 'vnukovo-masterplan-2018',
    title: 'Master Plan for Ground Infrastructure',
    airport: 'Vnukovo International Airport',
    location: 'Moscow',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '03/2018 – 07/2018',
    year: 2018,
    role: 'Project Manager',
    scope: 'Ground infrastructure master plan for Vnukovo Airport.',
  },
  {
    id: 'zhulyany-masterplan-2017',
    title: 'Master Plan',
    airport: 'Kyiv International Airport "Zhulyany"',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '10/2017 – 02/2018',
    year: 2018,
    role: 'Project Manager, Traffic Expert',
    scope: 'Full airport master plan including infrastructure and traffic projections.',
  },
  // ── 2017 ────────────────────────────────────────────────────────────────────
  {
    id: 'fortaleza-2016',
    title: 'Technical Advisory Services — 3rd Privatisation Round',
    airport: 'Fortaleza International Airport',
    location: 'Fortaleza',
    country: 'Brazil',
    region: 'Americas',
    period: '08/2016 – 02/2017',
    year: 2017,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic demand advisory for airport privatisation bid.',
  },
  {
    id: 'salvador-2016',
    title: 'Technical Advisory Services — 3rd Privatisation Round',
    airport: 'Salvador Bahia Airport',
    location: 'Salvador',
    country: 'Brazil',
    region: 'Americas',
    period: '08/2016 – 02/2017',
    year: 2017,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic demand advisory for airport privatisation bid.',
  },
  {
    id: 'pulkovo-growth-2017',
    title: 'Growth Strategy',
    airport: 'Pulkovo Airport',
    location: 'St. Petersburg',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '02/2017 – 03/2017',
    year: 2017,
    role: 'Project Manager, Traffic Expert',
    scope: 'Growth strategy development with long-term traffic projections.',
  },
  // ── 2016 ────────────────────────────────────────────────────────────────────
  {
    id: 'moldovan-airports-2015',
    title: 'Strategic Development — Study of Moldovan Airports',
    airport: 'Multiple airports',
    location: 'Moldova',
    country: 'Moldova',
    region: 'CIS & Eastern Europe',
    period: '2015 – 2016',
    year: 2016,
    role: 'Project Manager, Traffic Expert',
    scope: 'National airports strategic development study.',
  },
  // ── 2015 ────────────────────────────────────────────────────────────────────
  {
    id: 'romanian-airports-2014',
    title: 'Traffic Forecast for Regional Airports',
    airport: 'Multiple Regional Airports',
    location: 'Romania',
    country: 'Romania',
    region: 'CIS & Eastern Europe',
    period: '2014 – 2015',
    year: 2015,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic forecasting for multiple Romanian regional airports.',
  },
  // ── 2013–2014 ───────────────────────────────────────────────────────────────
  {
    id: 'donetsk-2013',
    title: 'Traffic Forecast & Market Study',
    airport: 'Donetsk International Airport',
    location: 'Donetsk',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '2013 – 2014',
    year: 2014,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic forecast and market analysis.',
  },
  // ── 2011–2012 ───────────────────────────────────────────────────────────────
  {
    id: 'kharkiv-business-plan-2011',
    title: 'Update Business Plan',
    airport: 'Kharkiv International Airport',
    location: 'Kharkiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '2011',
    year: 2011,
    role: 'Project Manager',
    scope: 'Comprehensive business plan update.',
  },
  {
    id: 'kharkiv-cargo-2011',
    title: 'Second Opinion on Cargo Concept',
    airport: 'Kharkiv International Airport',
    location: 'Kharkiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '03/2011 – 04/2011',
    year: 2011,
    role: 'Project Manager, Strategy Expert',
    scope: 'Independent second opinion on cargo development concept.',
  },
  {
    id: 'yaroslavl-strategic-2010',
    title: 'Strategic Development Concept',
    airport: 'Yaroslavl "Tunoshna" International Airport',
    location: 'Yaroslavl',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '09/2010 – 01/2011',
    year: 2011,
    role: 'Project Manager',
    scope: 'Strategic development concept for the airport.',
  },
  {
    id: 'yaroslavl-airline-marketing-2011',
    title: 'TSA — Airline Marketing',
    airport: 'Yaroslavl "Tunoshna" International Airport',
    location: 'Yaroslavl',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '2011 – stopped',
    year: 2011,
    role: 'Project Manager',
    scope: 'Target strategy and airline marketing programme.',
  },
  {
    id: 'basel-aero-landside-2010',
    title: 'Landside Development & Business Plan Update',
    airport: 'Basel Aero Airports (Krasnodar, Sochi, Gelendzhik & Anapa)',
    location: 'Krasnodar region',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '10/2010 – 12/2010',
    year: 2010,
    role: 'Project Manager, Traffic Expert',
    scope: 'Landside development concept and updated business plan for four airports.',
  },
  {
    id: 'odesa-prefeasibility-2010',
    title: 'Pre-feasibility Study',
    airport: 'Odesa International Airport',
    location: 'Odesa',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '04/2010 – 07/2010',
    year: 2010,
    role: 'Project Manager, Strategy & Traffic Expert',
    scope: 'Pre-feasibility study for airport development.',
  },
  // ── 2008–2009 ───────────────────────────────────────────────────────────────
  {
    id: 'tallinn-masterplan-2008',
    title: 'Master Plan Study',
    airport: 'Tallinn Airport',
    location: 'Tallinn',
    country: 'Estonia',
    region: 'Western Europe',
    period: '01/2008 – 01/2009',
    year: 2009,
    role: 'Deputy Project Manager & Traffic Expert',
    scope: 'Comprehensive master plan study for Tallinn Airport.',
  },
  {
    id: 'boryspil-masterplan-2008',
    title: 'Master Plan Update',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '12/2008 – 02/2009',
    year: 2009,
    role: 'Project Manager, Strategy & Traffic Expert',
    scope: 'Master plan update for Ukraine\'s main international airport.',
  },
  {
    id: 'basel-aero-positioning-2008',
    title: 'Strategic Positioning & Development Concept',
    airport: 'Basel Aero Airports (Krasnodar, Sochi, Gelendzhik & Anapa)',
    location: 'Krasnodar region',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '10/2008 – 01/2009',
    year: 2009,
    role: 'Project Manager, Traffic Expert',
    scope: 'Strategic positioning and development concept for airport group.',
  },
  {
    id: 'kharkiv-airline-marketing-2009',
    title: 'Airline Marketing',
    airport: 'Kharkiv International Airport',
    location: 'Kharkiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '2009',
    year: 2009,
    role: 'Deputy Project Manager',
    scope: 'Airline marketing programme and route development strategy.',
  },
  {
    id: 'kharkiv-masterplan-2007',
    title: 'Master Plan',
    airport: 'Kharkiv International Airport',
    location: 'Kharkiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '12/2007 – 02/2009',
    year: 2009,
    role: 'Deputy Project Manager',
    scope: 'Full airport master plan development.',
  },
  {
    id: 'ukraine-2020-2008',
    title: 'Ukrainian Airports Development to 2020',
    airport: 'All airports, Ukraine',
    location: 'Ukraine',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '09/2008 – 05/2009',
    year: 2009,
    role: 'Deputy Project Manager',
    scope: 'National airports development strategy to the year 2020.',
  },
  {
    id: 'limanskoe-2008',
    title: 'Strategic Development Concept & Positioning',
    airport: 'Limanskoe Airport',
    location: 'Limanskoe',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '07/2008 – 07/2009',
    year: 2009,
    role: 'Deputy Project Manager',
    scope: 'Strategic development concept and market positioning.',
  },
  {
    id: 'baikal-strategic-2007',
    title: 'Strategic Development (Feasibility Study)',
    airport: 'International Airport Ulan-Ude "Baikal"',
    location: 'Ulan-Ude',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '10/2007 – 07/2008',
    year: 2008,
    role: 'Deputy Project Manager',
    scope: 'Feasibility study and strategic development plan.',
  },
  {
    id: 'dubrovnik-2006',
    title: 'Master Plan & Strategic Development Concept',
    airport: 'Dubrovnik Airport',
    location: 'Dubrovnik',
    country: 'Croatia',
    region: 'Western Europe',
    period: '04/2006 – 01/2007',
    year: 2007,
    role: 'Traffic Forecast Expert',
    scope: 'Master plan and strategic development concept.',
  },
  {
    id: 'airports-south-russia-2007',
    title: 'Business Plan',
    airport: 'Airports of the South (Krasnodar, Sochi, Gelendzhik & Anapa)',
    location: 'Krasnodar region',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '02/2007 – 09/2007',
    year: 2007,
    role: 'Deputy Project Manager',
    scope: 'Business plan for southern Russian airport group.',
  },
  {
    id: 'lviv-2007',
    title: 'Strategic Development Concept',
    airport: 'Lviv Danylo Halytskyi International Airport',
    location: 'Lviv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '01/2007 – 04/2007',
    year: 2007,
    role: 'Deputy Project Manager',
    scope: 'Strategic development concept and market positioning.',
  },
  {
    id: 'kruger-mpumalanga-2004',
    title: 'Traffic Growth — Marketing & Sales Strategy',
    airport: 'Kruger Mpumalanga International Airport',
    location: 'Mbombela',
    country: 'South Africa',
    region: 'Africa',
    period: '2004 – 2007',
    year: 2007,
    role: 'Traffic Forecast Expert',
    scope: 'Traffic growth analysis and marketing & sales strategy.',
  },
  {
    id: 'pulkovo-forecast-2006',
    title: 'Comprehensive Traffic Forecast',
    airport: 'Pulkovo Airport',
    location: 'St. Petersburg',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '03/2006 – 04/2006',
    year: 2006,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Comprehensive long-term traffic demand forecast.',
  },
  {
    id: 'ufa-strategic-2005',
    title: 'Strategic Development Concept',
    airport: 'Ufa International Airport',
    location: 'Ufa',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '02/2005 – 08/2005',
    year: 2005,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Strategic development concept with traffic forecasting.',
  },
  {
    id: 'koltsovo-masterplan-2005',
    title: 'Update Masterplan',
    airport: 'Koltsovo Airport Ekaterinburg',
    location: 'Ekaterinburg',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '2005',
    year: 2005,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Masterplan update for Koltsovo Airport.',
  },
  {
    id: 'zhulyany-strategic-2005',
    title: 'Strategic Development Concept',
    airport: 'Kyiv International Airport "Zhulyany"',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '06/2005 – 10/2005',
    year: 2005,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Strategic development concept for Kyiv\'s secondary airport.',
  },
  {
    id: 'boryspil-masterplan-2003',
    title: 'Update Masterplan',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '9/2003 – 01/2004',
    year: 2004,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Masterplan update for Ukraine\'s principal international airport.',
  },
  {
    id: 'boryspil-aerohandling-2004',
    title: 'Concept for Ground Handling Company (Aerohandling Ltd.)',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '2004',
    year: 2004,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Development concept for new ground handling subsidiary.',
  },
  {
    id: 'sheremetyevo-concept-2004',
    title: 'Preparation of Airport Development Concept',
    airport: 'Sheremetyevo International Airport',
    location: 'Moscow',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '2004',
    year: 2004,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Airport development concept study.',
  },
  {
    id: 'boryspil-terminal-tender-2003',
    title: 'Design & Supervision Tender for New Passenger Terminal',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '07/2003 – 12/2003',
    year: 2003,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Preparation and management of design and supervision tender.',
  },
  {
    id: 'boryspil-terminal-prefeasibility-2003',
    title: 'Pre-feasibility Study for New Passenger Terminal',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '2003',
    year: 2003,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Pre-feasibility study for the new passenger terminal that would become Terminal D.',
  },
  {
    id: 'sheremetyevo-operator-2003',
    title: 'Support for Management in Providing Airport Operator',
    airport: 'Sheremetyevo International Airport',
    location: 'Moscow',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '11/2003 – 12/2003',
    year: 2003,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Management support for airport operator selection.',
  },
  {
    id: 'sheremetyevo-management-2003',
    title: 'Provision of Management for Operating Company',
    airport: 'Sheremetyevo International Airport',
    location: 'Moscow',
    country: 'Russia',
    region: 'CIS & Eastern Europe',
    period: '2003',
    year: 2003,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Management support for airport operating company.',
  },
  {
    id: 'boryspil-ground-handling-training-2000',
    title: 'Ground Handling Training',
    airport: 'Boryspil International Airport',
    location: 'Kyiv',
    country: 'Ukraine',
    region: 'CIS & Eastern Europe',
    period: '2000',
    year: 2000,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Ground handling operations training programme.',
  },
  {
    id: 'tajikistan-2000',
    title: 'Restructuring Study of National Air Company',
    airport: 'Dushanbe & Khujand Airports',
    location: 'Dushanbe & Khujand',
    country: 'Tajikistan',
    region: 'CIS & Eastern Europe',
    period: '03/2000 – 12/2002',
    year: 2002,
    role: 'Deputy Project Manager, Traffic Forecast Expert',
    scope: 'Restructuring study for Tajikistan State Air Company.',
    client: 'World Bank / TACIS',
  },
]

// ── Helpers ──────────────────────────────────────────────────────────────────

export const featuredProjects = projects.filter((p) => p.highlight)

export const projectsByRegion = projects.reduce<Record<ProjectRegion, Project[]>>(
  (acc, project) => {
    if (!acc[project.region]) acc[project.region] = []
    acc[project.region].push(project)
    return acc
  },
  {} as Record<ProjectRegion, Project[]>,
)

export const regionOrder: ProjectRegion[] = [
  'CIS & Eastern Europe',
  'Western Europe',
  'Africa',
  'Asia & Pacific',
  'Middle East',
  'Americas',
]
